use_frameworks!

platform :ios, '8.0'

target 'cwdTest_Example' do
#  pod 'cwdTest', :path => '../'
  pod 'cwdTest', :git => 'https://github.com/Chailang/cwdTest.git'

  pod 'AFNetworking'
  target 'cwdTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

